/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BeButton: typeof import('./src/components/Button/BeButton.vue')['default']
    BeIcon: typeof import('./src/components/Icon/BeIcon.vue')['default']
    BeLoading: typeof import('./src/components/Loading/BeLoading.vue')['default']
    BeSwitch: typeof import('./src/components/Switch/BeSwitch.vue')['default']
  }
}
